# Generated by Django 3.0.5 on 2020-04-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cran', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'version')},
        ),
    ]
